import TopBar from '@app/components/top-bar/TopBar';
import Button from '@app/shared/buttons/button/Button';
import Head from 'next/head';

import MainNav from '@app/components/main-nav/MainNav';
import { useLang } from '@app/context/lang.context';

export default function Home() {
    const { langData } = useLang();
    const btnData =
        langData && langData.menuBar ? langData.menuBar.accountBtn : null;

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {btnData && (
                <main>
                    <TopBar />
                    <MainNav sampleTextProp="test" />
                    <Button>{langData.test}</Button>
                    <Button>Coucou toi</Button>
                </main>
            )}
        </>
    );
}
