import TopBar from '@app/components/top-bar/TopBar';
import Button from '@app/shared/buttons/button/Button';
import Head from 'next/head';
export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <TopBar />
                <Button>Pas oublier de me typer</Button>
                <Button>Coucou toi</Button>
            </main>
        </>
    );
}
