import TopBar from '@app/components/top-bar/TopBar';
import Head from 'next/head';

import MainNav from '@app/components/main-nav/MainNav';
import { useLang } from '@app/context/lang.context';
import BigBlock from '@app/shared/layout/bigBlock/BigBlock';
import CardList from '@app/shared/layout/cardList/CardList';
import Media from '@app/shared/layout/media/Media';
import Swipper from '@app/shared/layout/swipper/Swipper';

export default function Home() {
    const { langData } = useLang();
    const btnData =
        langData && langData.menuBar ? langData.menuBar.accountBtn : null;
    const bigBlockData = langData.bigBlock;
    const travelData = langData.travel;
    const offersData = langData.offers;
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {btnData && (
                <main>
                    <header className="app-header">
                        <TopBar />
                        <MainNav />
                    </header>
                    <BigBlock
                        title={bigBlockData.title}
                        btn={bigBlockData.btn.name}
                        img={bigBlockData.img}
                        url={bigBlockData.btn.url}
                    ></BigBlock>
                    <Media title={travelData.title} text={travelData.text}>
                        <Swipper swiperData={travelData.swiper} />
                    </Media>
                    <CardList
                        title={offersData.title}
                        data={offersData.list}
                        btn={offersData.btn}
                    />
                </main>
            )}
        </>
    );
}
